version: '3.2'
services:
  jupyterhub:
    image: jupyterhub/jupyterhub:latest
    container_name: jupyterhub
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
  jupyterlab:
    image: jupyter/datascience-notebook:latest
    command: echo
  postgis:
    image: kartoza/postgis:14-3.2
    ports:
      - 5432:5432
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=robindu
      - POSTGRES_DBNAME=Each
      - POSTGRES_PASS=*******
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
      - postgres:/var/lib/postgresql
    restart: always
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin4:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=robin.du@each.com.au
      - PGADMIN_DEFAULT_PASSWORD=*******

volumes:
  jupyterhub_data:
  postgres:
  pgadmin4:
