version: '3.2'
services:
  jupyterhub:
    image: jupyterhub/jupyterhub:2.3.0
    container_name: jupyterhub
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
  jupyterlab:
    image: jupyter/datascience-notebook:latest
    command: echo
  postgis:
    image: kartoza/postgis:14-3.2
    container_name: postgis
    ports:
      - 5432:5432
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=robindu
      - POSTGRES_DBNAME=Each
      - POSTGRES_PASS=Each2022
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
      - postgres:/var/lib/postgresql
    restart: always
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin4:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=robin.du@each.com.au
      - PGADMIN_DEFAULT_PASSWORD=Each2020
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/SuansToy
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
  django_api:
    image: robin0821/power-api:latest
    container_name: django
    restart: always
    volumes:
      - geodjango_main:/opt/services/djangoapp/src
      - geodjango_nginx:/opt/services/djangoapp/src/config/nginx/conf.d
      - static_volume:/opt/services/djangoapp/src/static
      - media_volume:/opt/services/djangoapp/src/media
    depends_on:
      - postgis
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - geodjango_nginx:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/src/static
    depends_on:
      - django_api 
  nlp:
    image: johnsnowlabs/nlp-server:latest
    container_name: nlp
    restart: always
    pull_policy: always
    ports:
      - 5000:5000
    volumes:
      - cache_pretrained:/home/johnsnowlabs/cache_pretrained
  tensorflow:
    image: tensorflow/tensorflow:latest-jupyter
    container_name: tensorflow
    restart: on-failure
    user: "${UID}:${GID}"
    ports:
      - 8888:8888
    volumes:
      - /home/robinduadmin/work:/tf/notebooks
  
volumes:
  jupyterhub_data:
  postgres:
  pgadmin4:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  geodjango_main:
  geodjango_nginx:
  static_volume:
  media_volume:  
  cache_pretrained:
